all:
  hosts:
    test1:
      ansible_user: alex
      ansible_port: 22100
      ansible_host: 127.0.0.1
      ansible_password: "alex"
      ansible_sudo_pass: "alex"
    test2:
      ansible_user: alex
      ansible_port: 22102
      ansible_host: 127.0.0.1
      ansible_password: "alex"
      ansible_sudo_pass: "alex"
###смена порта
## https://vps.ua/wiki/changing-ssh-port/
# netstat -tupln | grep LISTEN
# nano /etc/ssh/sshd_config
# systemctl restart sshd.service

###root по ssh без пароля
## https://andreyex.ru/novosti/kak-zapuskat-komandy-sudo-bez-parolya/
# Но сначала сделайте резервную копию файла sudoer в качестве меры предосторожности:
# sudo cp /etc/sudoers ~/sudoers.bak

# Используйте следующую команду для редактирования файла /etc/sudoers:
# sudo visudo

# Все, что вам нужно сделать, это добавить строку в этом файле:
# user_name ALL=(ALL) NOPASSWD:ALL
# в моем случае
# alex ALL=(ALL) NOPASSWD:ALL


# про ловлю ошибок
# https://docs.ansible.com/ansible/latest/user_guide/playbooks_error_handling.html
# https://docs.ansible.com/ansible/latest/user_guide/playbooks_blocks.html#block-error-handling

# про установку и удаление модулей
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/package_module.html
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/yum_module.html

# про sudo
# https://ealebed.github.io/posts/2017/ansible-%D0%B2%D0%B2%D0%BE%D0%B4-sudo-%D0%BF%D0%B0%D1%80%D0%BE%D0%BB%D1%8F-%D0%BF%D1%80%D0%B8-%D0%B2%D1%8B%D0%BF%D0%BE%D0%BB%D0%BD%D0%B5%D0%BD%D0%B8%D0%B8-playbook/

# ./ansible all -m ping -i ./hosts.yaml

# ./ansible-playbook ./play.yaml -i ./hosts.yaml | grep -E '(-OK|-FAIL)' -o | grep -E '(OK|FAIL)' -o

# про become
# https://docs.ansible.com/ansible/2.4/become.html#:~:text=Ansible%20allows%20you%20to%20'become,dzdo%20%2C%20ksu%20%2C%20and%20others.